### PR TITLE
fixed problems loading single functions of the package without loading the package as a whole

### PR DESCRIPTION
**Pull request by tscheypidi**
Hi,

I am importing the functions WDIcache and WDIsearch in another R package I am currently working on. Doing so I realized that both functions only work if the WDI package is loaded in advance (e.g. WDI::WDIcache() or WDI::WDIsearch() both stop with an error if the package has not been loaded).

The problem can be fixed by addressing fromJSON and WDI_data with the source they are coming from. I modified the code accordingly (sorry for the different line endings).

By accepting my pull request the problem should be solved.

Best, Jan

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Thanks a lot for this contribution, Jan! 3 points:

1. At the moment, I can't review the code changes because the diff is useless (every line has changed). Did you change the white space or something?

2. There can't be any manual changes to NAMESPACE, since they will be overwritten the next time I run roxygen2

3. Do you need this in a CRAN release? It's a bit of pain to make an official release for such a minor change... (But not absolutely prohibitive, of course)

**Comment by tscheypidi** [comment]
@1: sorry for that. I just noticed it after submitting my commit. I made the following changes:
- line 19:  @importFrom RJSONIO fromJSON (added line)
- line 114:  series_dat    = RJSONIO::fromJSON(series_url, nullValue=NA)[[2]]) (added RJSONIO::)
- line 121:  country_dat = RJSONIO::fromJSON(country_url, nullValue=NA)[[2]] (added RJSONIO::)
- line 154: series = WDI::WDI_data$series (added WDI::)

@2 I created the updated NAMESPACE using roxygen via the importFrom statement mentioned above

@3 An official release would be really good. The changes I did were minor, but without it, it is currently impossible to properly import the WDI package in other packages (the only workaround is to set WDI as "depends" rather than "imports" which is not recommended as explained here: http://r-pkgs.had.co.nz/description.html) You could also think about moving RJSONIO from depends to imports in the DESCRIPTION to be in line with current recommendations, but this is not necessary to have the import properly working in other packages.

**Comment by vincentarelbundock** [comment]
OK, sounds great.

Could you please make a new PR with spaces instead of tabs, and maybe you can make the change you recommend in DESCRIPTION too. After that, I can prep a release to CRAN.

**Comment by vincentarelbundock** [comment]
FYI, I submitted the package to CRAN a minute ago. Hopefully there won't be anything to fix and we can all enjoy a new live version soon.

Thanks again!

**Comment by tscheypidi** [comment]
Thanks!

**Pull request merged**
