### PR TITLE
update WDIbulk with tidyr function and speed

### PR DESCRIPTION
**Pull request by etiennebacher**
I changed two things in `WDIbulk()`:

* `unz()` was in the loop to read the CSV files, which unnecessarily increased the processing time since the compressed folder only needs to be unzipped once. This should allow to gain some time, but I was unable to check this as I had a timeout issue each time I tried to download the compressed folder. So it would be nice if you (or someone else) with a better Internet connection could test if this change increases speed.

* I updated `tidyr::gather()` into `tidyr::pivot_longer()` as the former is now "retired". 

PS: RStudio automatically fixed indentation on the whole file, which explains why GitHub shows that many lines have been changed. The code changes are only in `WDIbulk()`.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Sounds wonderful, thanks so much!

Would you mind making a PR without the change in indentation. 4 vs. 2 is an arbitrary convention, and changing it halfway just makes the history and diffs very hard to compare/follow. , I'd prefer to leave it like that. Also makes it hard to see if inadvertent changes were made at the same time. Since the project was started with 4.

Aside from that, this seems like a straightfoward change, so it should be an easy merge.

Thanks!

**Comment by etiennebacher** [comment]
Sure, I'll put the indentation as it was before

**Comment by etiennebacher** [comment]
Done, I also forgot to unlink `temp_file` (it was still on `temp`, which doesn't exist anymore). This is fixed

**Comment by vincentarelbundock** [comment]
Looks great! I made a few minor changes, including the addition of a `timeout` argument so you hopefully won't run into the same issue with the download failing.

Everything is merged here: https://github.com/vincentarelbundock/WDI/commit/025f6abb365d300b4868ff0e207cdd2e5e5c587f

Thanks again!

**Pull request closed without merging**
