### PR TITLE
Use Markdown formatting in docs

### PR DESCRIPTION
**Pull request by etiennebacher**
I just realized that markdown syntax is used in (part of) the docs but wasn't properly rendered (see for instance the `*` not rendered as bullet points in `?languages_supported`). This PR fixes that and one `roxygen2` warning about the deprecated usage of `@docType package`.

---

Edit: used this occasion to also update the CI workflow

### CODE REVIEW

**Comment by etiennebacher** [comment]
@vincentarelbundock `wdi.dl` and `wdi.query` have the following:

```
#' @export
#' @keywords internal
#' @noRd
```

which generates a warning `Undocumented code objects`. Should they be internal or exported? I guess they should be exported otherwise that would be a breaking change and they could just inherit the docs from other functions but I'd like you to confirm before I spend time on this.

**Comment by vincentarelbundock** [comment]
yeah, IIRC, these were never intended to be exported. So it's a breaking change but only because of a docs issue.

I'm happy with any solution you want to implmeent

**Comment by etiennebacher** [comment]
I removed them since it's the fastest to do and they have "internal function" in the title anyway

**Comment by etiennebacher** [comment]
Do you have any idea why this fails?

``` r
library(WDI)
cache = WDIcache()
old <- WDIsearch('gdp.*capita.*constant')
new <- WDIsearch("gdp.*capita.*constant", cache = cache)

waldo::compare(old, new)
#> `attr(old, 'row.names')`: 717 11431 11433 11435 11436
#> `attr(new, 'row.names')`: 692 12372 12374 12376 12377
#> 
#> old vs new
#>                                                            name
#>   old[1, ] GDP per capita, PPP (constant 2011 international $) 
#>   old[2, ] GDP per capita (constant 2015 US$)                  
#>   old[3, ] GDP per capita (constant LCU)                       
#> - old[4, ] GDP per capita, PPP (constant 2017 international $) 
#> + new[4, ] GDP per capita, PPP (constant 2021 international $) 
#>   old[5, ] GDP per capita, PPP (constant 1987 international $) 
#> 
#> old$name vs new$name
#>   "GDP per capita, PPP (constant 2011 international $) "
#>   "GDP per capita (constant 2015 US$)"
#>   "GDP per capita (constant LCU)"
#> - "GDP per capita, PPP (constant 2017 international $)"
#> + "GDP per capita, PPP (constant 2021 international $)"
#>   "GDP per capita, PPP (constant 1987 international $)"
```

My guess is that we should update `data/WDI_data.RData` but I don't know how. (Sorry, I thought this would be a routine PR)

**Comment by vincentarelbundock** [comment]
Yep, I think that's the problem.

I pushed a new search cache and added a note to the readme to indicate how to do it.

**Comment by vincentarelbundock** [comment]
Thanks!

**Pull request merged**
